export const EMPLOYEE_LOADED = 'EMPLOYEE_LOADED';
export const EMPLOYEE_LOAD_ERROR = 'EMPLOYEE_LOAD_ERROR';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const DISPLAY_EDIT_EMPLOYEE = 'DISPLAY_EDIT_EMPLOYEE';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
